
spring:
  application:
    name: property-gateway
  cloud:
    gateway:
      routes:
        - id: property-service
          uri: lb://PROPERTY-SERVICE
          predicates:
            - Path=/api/v1/listings/**
        - id: property-user-service
          uri: lb://PROPERTY-USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
server:
  port: 8080
