
spring:
  application:
    name: property-gateway
  cloud:
    gateway:
      routes:
        - id: property-listing-service
          uri: lb://PROPERTY-LISTING-SERVICE
          predicates:
            - Path=/api/v1/listings/**
        - id: property-user-service
          uri: lb://PROPERTY-USER-SERVICE
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**
server:
  port: 8080
